Add minimum dependencies sets to travis build

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,40 +1,68 @@
-# NB: don't set `language: haskell` here
-
-# The following enables several GHC versions to be tested; often it's enough to test only against the last release in a major GHC version. Feel free to omit lines listings versions you don't need/want testing for.
 env:
- - CABALVER=1.18 GHCVER=7.6.3
+ - CABALVER=1.22 GHCVER=7.10.2
  - CABALVER=1.18 GHCVER=7.8.4
- - CABALVER=1.22 GHCVER=7.10.1
- - CABALVER=head GHCVER=head  # see section about GHC HEAD snapshots
+ - CABALVER=1.18 GHCVER=7.6.3
+ # Depency set frozen to be in sync with Debian Jessie Haskell packages.
+ # Dependencies not present in Debian use the cabal solver. This includes
+ # direct dependencies too.
+ - CUSTOMSET=jessie
+ # Direct dependencies set to the minimum bounds. Transitive depencies use
+ # cabal solver.
+ - CUSTOMSET=minimum
+ # Minimum dependencies for direct depencies and Depency set frozen to be in
+ # sync with Debian Jessie Haskell packages.  Dependencies not present in
+ # Debian use the cabal solver.
+ - CUSTOMSET=jessie-minimum
+ - CABALVER=head GHCVER=head
 
 matrix:
   allow_failures:
    - env: CABALVER=head GHCVER=head
 
-# Note: the distinction between `before_install` and `install` is not important.
 before_install:
+ - case "$CUSTOMSET" in
+    "") ;;
+
+    "jessie")
+      export CABALVER=1.20 ;
+      export GHCVER=7.6.3 ;
+      mv cabal-deb.config cabal.config ;;
+
+    "minimum")
+      export CABALVER=1.20 ;
+      export GHCVER=7.6.3 ;
+      mv cabal-min.config cabal.config ;;
+
+    "jessie-minimum")
+      export CABALVER=1.20 ;
+      export GHCVER=7.6.3 ;
+      cat cabal-deb.config cabal-min.config > cabal.config ;;
+
+    *)
+      export GHCVER=unknown ;
+      echo "unknown/invalid depency set requested" ;
+      exit 1 ;;
+    esac
+
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
- - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
- - travis_retry sudo apt-get install libxss-dev
+ - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 
 install:
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - travis_retry cabal update
- - cabal install --only-dependencies --enable-tests --enable-benchmarks
+ - cabal install --only-dependencies --enable-tests
 
-# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
 script:
  - if [ -f configure.ac ]; then autoreconf -i; fi
- - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
- - cabal build   # this builds all libraries and executables (including tests/benchmarks)
+ - cabal configure --enable-tests -v2
+ - cabal build
  - cabal test
  - cabal check
- - cabal sdist   # tests that a source-distribution can be generated
+ - cabal sdist
 
-# The following scriptlet checks that the resulting source distribution can be built & installed
  - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
    cd dist/;
    if [ -f "$SRC_TGZ" ]; then
